### ISSUE TITLE
declining due to bad method: POST

### ISSUE THREAD

**Issue by Tzwen78** [bombadil/mod_proxy_msrpc#12] opened 2013-12-19 13:14 UTC
Hi,

i’m testing Apache as Reverse-Proxy für our Exchange SRV. Fortunately I found this module so we are able to use Outlook Anywhere.

Last week I set up the module and it seems to work perfect with Outlook Anywhere.

 Now it doesn’t anymore. No connection with OL Anywhere could be established. It’s not possible to authenticate. The authentication window pops up.

I added  “LogLevel info proxy_msrpc:trace2” to my config and now I could see the following entries in my apache.log, when I try to establish a connation via ol anywhere.

[proxy_msrpc:debug] [pid 32186:tid 139986967930624] mod_proxy_msrpc.c(1233): [client 80.187.102.60:23872] declining due to bad method: POST
 [proxy_msrpc:debug] [pid 32186:tid 139986934359808] mod_proxy_msrpc.c(1233): [client 80.187.105.34:18060] declining due to bad method: POST
 [proxy_msrpc:debug] [pid 32187:tid 139987163571968] mod_proxy_msrpc.c(1233): [client 80.187.105.34:12731] declining due to bad method: POST

I’m a newbie with apache and such modules, so I hope you could assist me to get OL Anywhere working.

Thanks.

**Comment by bombadil** [comment] 2013-12-22 15:56
Does it work if you disable NTLM authentication?

**Comment by Tzwen78** [comment] 2013-12-23 10:19
Hi Micha,

thanks for replay. Unfortunately not. I tried with “Standard Auth” before I opened this issue.

In January I’m back in office and will do some further test. If something changed e.g in log I will post it here.

Merry Xmas.

**Comment by Tzwen78** [comment] 2014-01-07 12:44
Hi,

I’m back in office an did some further tests.

I could see the same entries in Apache Log even I switch to “Standard Auth” in Exchange. So OL-Anywhere is still not working and prompts for authentication. 

[Tue Jan 07 11:26:22.163470 2014] [proxy_msrpc:debug] [pid 13945:tid 139947256235776] mod_proxy_msrpc.c(1233): [client80.187.109.178:21112
] declining due to bad method: POST

I’m confused about the logged IP. It’s the IP of my mobile test-device and I get such error messages even I do not try to use OL-Anywhere.

Thank you for further assist.

**Comment by teckert** [comment] 2014-01-28 10:15
Tzwen78, there should not be a HTTP POST inside Outlook Anywhere traffic. This seems to me like the Autodiscover traffic is mixed up with the Outlook Anwhere traffic. That's a common problem but easy to fix with the correct configuration.
There will be an example for a correct config here soon.

**Comment by Tzwen78** [comment] 2014-01-28 11:43
Hi teckert, many thanks for your replay. At this moment i dont't realy understand what you mean with the correct configuration or where this configuration has to do (in Exchange or Reverse-Proxy?). So i look forward for an example.

**Comment by bombadil** [comment] 2014-01-28 19:41
Hi Tzwen, as teckert mentioned above, POST requests are unrelated to Outlook Anywhere traffic. For this reason mod_proxy_msrpc declines handling them, which means they get handled by Apache httpd's usual reverse proxying mechanisms for HTTP, i.e. mod_proxy_http. You can see this confirmed in detail if you add following directive to the configuration:

```
LogLevel info proxy_msrpc:trace2 proxy:debug proxy_http:debug
```

All this does not mean that this traffic is not generated by Outlook. E.g. some Outlook versions use autodiscovery to automatically detect most (if not all) configuration settings. If autodiscovery is configured to authenticate using NTLM, this will fail because of https://issues.apache.org/bugzilla/show_bug.cgi?id=40029. But there are several other reasons why autodiscovery might not work when used via a reverse proxy (Apache). For this reason you may need to initially configure and setup your Outlook without Apache between Outlook and Exchange. As soon as you have verified this to work, you can change your network setup so that Outlook will connect through Apache and mod_proxy_msrpc.

Regarding the configuration examples please be patient.

**Comment by Tzwen78** [comment] 2014-02-05 06:47
Hi Micha and teckert, sorry for the delay.

Before i started working with Apache and your modul,  my OL 2010 Clients where directly (through Firewall) conected to Exchange 2010. Autodiscover and OL Anywhere with NTLM where working fine.

Then i tried some Reverse Proxy Solutions, like the Loadbalancer KEMP and Debian + HAProxy. Both are working fine too. I understood that apache is not working with NTLM  / OL Anywhere anymore and i need your modul. B.T.W. OWA + ActiveSync works with my Apache Configuration. I only get some timeout errors in the Apache Log from the mobile Devices.

So i don’t understand what i can do or change in my configuration to get OL Anywhere working with Apache. I will wait and see for an  configuartion example.

**Comment by ccesario** [comment] 2015-11-17 17:11
Hello,

I'm too getting this error when try access by Mobile device (ActiveSync) even when BasicAuth is enabled in EWS.

 Nov 17 13:16:29.098420 2015] [proxy_msrpc:debug] [pid 11443] mod_proxy_msrpc.c(1276): [client 192.168.X.X:35798] declining due to bad method: POST
[Tue Nov 17 13:16:29.098469 2015] [proxy:error] [pid 11443] AH00940: HTTPS: disabled connection for (192.168.Y.Y)
[Tue Nov 17 13:16:29.184187 2015] [proxy_msrpc:debug] [pid 11531] mod_proxy_msrpc.c(1276): [client 192.168.X.X:56741] declining due to bad method: POST
[Tue Nov 17 13:16:29.184247 2015] [proxy:error] [pid 11531] AH00940: HTTPS: disabled connection for (192.168.Y.Y)
[Tue Nov 17 13:16:29.259163 2015] [proxy_msrpc:debug] [pid 11324] mod_proxy_msrpc.c(1276): [client 192.168.X.X:37418] declining due to bad method: POST
[Tue Nov 17 13:16:29.259201 2015] [proxy:error] [pid 11324] AH00940: HTTPS: disabled connection for (192.168.Y.Y)
[Tue Nov 17 13:16:29.343817 2015] [proxy_msrpc:debug] [pid 11670] mod_proxy_msrpc.c(1276): [client 192.168.X.X:44445] declining due to bad method: POST

Does someone have idea about fix it ?

Best regards

**Comment by bombadil** [comment] 2015-11-18 07:40
Hi Cesario,

POST request are not part of the RPC over HTTP protocol that is handled by mod_proxy_msrpc (this is what the debug message "declining due to bad method" means). So if you believe Outlook Anywhere doesn't work for the requests that generate these messages in the logs, you should check the configuration of other Apache proxy modules, because these should handle them, not mod_proxy_msrpc.

Hope this helps,

Micha

**Comment by bombadil** [comment] 2020-11-10 19:19
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).

**Closed as completed by bombadil** 2020-11-10 19:19 UTC
Labels: question, wontfix
