### ISSUE TITLE
Unexpected status code 200

### ISSUE THREAD

**Issue by edieterich** [bombadil/mod_proxy_msrpc#26] opened 2014-09-17 13:25 UTC
Running the "Outlook Connectivity" test from the [Microsoft Remote Connectivity Analzyer](https://testconnectivity.microsoft.com/) against an Exchange 2010 server fails:

> Attempting to ping the MAPI Mail Store endpoint with identity: SRV-EXCH01.DEMO.local:6001.
>      The attempt to ping the endpoint failed.
>       Tell me more about this issue and how to resolve it
> 
> ```
> Additional Details
> ```
> 
> The RPC_S_SERVER_UNAVAILABLE error (0x6ba) was thrown by the RPC Runtime process.
> Elapsed Time: 319009 ms.

The Apache log shows an "unexpected status code 200" error:

```
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.141969 2014] [proxy_msrpc:trace1] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1282): [client 134.170.52.124:60380] RPC_IN_DATA: serving URL https://172.31.1.249/Rpc/RpcProxy.dll?SRV-EXCH01.DEMO.local:6001
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.141992 2014] [proxy_msrpc:trace2] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1077): [client 134.170.52.124:60380] RPC_IN_DATA: re-using already established connection 0x92daf60 to backend: 172.31.1.249
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.142106 2014] [proxy_msrpc:trace1] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1309): [client 134.170.52.124:60380] RPC_IN_DATA: HTTP request sent to (null) (172.31.1.249), now waiting for a response
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.144968 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(924): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response status line (status code: 200)
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145038 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line [Content-Length: 20]
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145050 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line [Content-Type: application/rpc]
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145060 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line [Server: Microsoft-IIS/7.5]
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145070 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line [X-Powered-By: ASP.NET]
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145080 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line [Date: Wed, 02 Jul 2014 08:44:15 GMT]
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145089 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(962): [client 134.170.52.124:60380] RPC_IN_DATA: Got HTTP response header line []
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.145096 2014] [proxy_msrpc:trace3] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(980): [client 134.170.52.124:60380] RPC_IN_DATA: Got all HTTP response headers from server
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146325 2014] [proxy_msrpc:trace2] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1011): [client 134.170.52.124:60380] RPC_IN_DATA: Forwarded all HTTP response headers to client
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146344 2014] [proxy_msrpc:trace2] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1021): [client 134.170.52.124:60380] RPC_IN_DATA: HTTP response body size: 20 bytes
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146492 2014] [proxy_msrpc:debug] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1048): [client 134.170.52.124:60380] RPC_IN_DATA: Forwarded the HTTP response to client
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146509 2014] [proxy_msrpc:trace2] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1314): [client 134.170.52.124:60380] RPC_IN_DATA: proxy_msrpc_read_server_response() returned status code 200
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146518 2014] [proxy_msrpc:info] [pid 4428:tid 2720541552] [client 134.170.52.124:60380] RPC_IN_DATA: proxy_msrpc_read_server_response() returned unexpected status code 200 from (null) (172.31.1.249)
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: [Wed Jul 02 10:44:11.146526 2014] [proxy_msrpc:trace2] [pid 4428:tid 2720541552] mod_proxy_msrpc.c(1322): [client 134.170.52.124:60380] RPC_IN_DATA: proxy_msrpc_handler finished for request without body
2014:07:02-10:44:11 NMG-UTM-02 reverseproxy: srcip="134.170.52.124" localip="10.128.197.52" size="20" user="-" host="134.170.52.124" method="RPC_IN_DATA" statuscode="200" reason="-" extra="-" exceptions="SkipURLHardening" time="8021" url="/Rpc/RpcProxy.dll" server="oa.test.example.org" referer="-" cookie="-" set-cookie="-"
```

This is the offending request sent from Apache to Exchange:

```
RPC_IN_DATA https://172.31.1.249/Rpc/RpcProxy.dll?SRV-EXCH01.DEMO.local:6001 HTTP/1.1
Authorization: Basic ZGVtby5sb2NhbFx0ZXN0OnBhc3N3b3JkCg==
Accept: application/rpc
User-Agent: MSRPC
Host: oa.test.example.org
Content-Length: 0
X-Forwarded-Proto: https
```

And the response from Exchange:

```
HTTP/1.1 200 Success
Content-Length: 20
Content-Type: application/rpc
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Fri, 12 Sep 2014 11:36:23 GMT

<binary data>
```

Outlook with OA seems to run fine.

**Comment by bombadil** [comment] 2014-10-15 12:25
From reading the code I don't understand how the unexpected status code 200 does harm more than adding an error message.

Maybe we need to figure out what these 20 bytes binary data in the server response are.

**Comment by jcnengel** [comment] 2015-09-20 20:05
I hit this bug whilst trying to hunt down the root cause for the failure of the Remote Connectivity Analyzer due to a RPC_S_SERVER_UNAVAILABLE-Fehler (0x6ba) pinging the MAPI store. Have not yet found a solution...

**Comment by edieterich** [comment] 2015-09-21 06:46
The real cause for the RPC_S_SERVER_UNAVAILABLE error (0x6ba) seems to be an Echo request that the client is sending (wireshark calls it "Echo"). The log message about the unexpected status code 200 has nothing to do with the failing Remote Connectivity Tester run. It looks like this situation is handled correctly by mod mod_proxy_msrpc.

Here's the Echo request sent by the client:

```
RPC_IN_DATA /rpc/rpcproxy.dll?waf-ms9-ex1.ms9.local:6001 HTTP/1.1
[...]
Content-Length: 4
[...]

<binary data: f8 e8 18 08 (not sure if it's always the same)>
```

So only 4 bytes of payload. But in proxy_msrpc_read_and_parse_initial_pdu() ap_get_brigade() is called in a loop to read at least 10 bytes of payload (MSRPC_PDU_MINLENGTH). This means that after 4 bytes are read, the next call of ap_get_brigade() to read the missing 6+ bytes blocks, leading to a timeout. Here are the relevant log lines, confirming the timeout:

```
2014:10:20-15:11:06 waf-ms9-utm1 reverseproxy: [Mon Oct 20 15:11:06.374886 2014] [proxy_msrpc:trace2] [pid 22163:tid 4054711152] mod_proxy_msrpc.c(733): [client 10.8.26.36:34562] RPC_IN_DATA: got 4 bytes of request body from client
2014:10:20-15:16:06 waf-ms9-utm1 reverseproxy: [Mon Oct 20 15:16:06.466563 2014] [proxy_msrpc:error] [pid 22163:tid 4054711152] (70007)The timeout specified has expired: [client 10.8.26.36:34562] RPC_IN_DATA: failed to read request body - ap_get_brigade
2014:10:20-15:16:06 waf-ms9-utm1 reverseproxy: [Mon Oct 20 15:16:06.466670 2014] [proxy_msrpc:trace2] [pid 22163:tid 4054711152] mod_proxy_msrpc.c(1492): [client 10.8.26.36:34562] RPC_IN_DATA: handler working on backend connection 0x8da3360 finished, returning connection to pool
2014:10:20-15:16:06 waf-ms9-utm1 reverseproxy: [Mon Oct 20 15:16:06.466716 2014] [proxy_msrpc:trace2] [pid 22163:tid 4054711152] mod_proxy_msrpc.c(1497): [client 10.8.26.36:34562] RPC_IN_DATA: setting keepalive from 0 to AP_CONN_CLOSE
```

But as stated earlier, Outlook with OA is running fine.

**Comment by aledr** [comment] 2016-05-02 06:55
@jcnengel same here... Was you able to find a fix?

**Comment by bombadil** [comment] 2020-11-10 19:17
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).

**Closed as completed by bombadil** 2020-11-10 19:17 UTC
Labels: bug, wontfix
